package com.trustableai.koru.runtime

import com.trustableai.koru.model.Corner
import com.trustableai.koru.model.Track

object TrackCatalog {
    val sonomaRaceway =
        Track(
            name = "Sonoma Raceway",
            lengthMeters = 4031.38,
            centerLat = 38.16152,
            centerLon = -122.45472,
            corners =
                listOf(
                    Corner(
                        id = 1,
                        name = "Turn 1",
                        entryDist = 80.0,
                        apexDist = 120.0,
                        exitDist = 170.0,
                        lat = 38.16180,
                        lon = -122.45550,
                        advice = "Brake straight, settle the platform, and commit to a clean turn-in.",
                        entryLat = 38.16200,
                        entryLon = -122.45500,
                        targetSpeed = 55.0,
                    ),
                    Corner(
                        id = 2,
                        name = "Turn 2",
                        entryDist = 300.0,
                        apexDist = 390.0,
                        exitDist = 470.0,
                        lat = 38.16120,
                        lon = -122.45680,
                        advice = "Stay wide, trail brake in, use the apex curb, and throttle at the curb.",
                        entryLat = 38.16150,
                        entryLon = -122.45620,
                        targetSpeed = 70.0,
                    ),
                    Corner(
                        id = 3,
                        name = "Turn 3",
                        entryDist = 560.0,
                        apexDist = 640.0,
                        exitDist = 720.0,
                        lat = 38.16050,
                        lon = -122.45750,
                        advice = "Slow in, fast out. Late apex and wait longer than you think for throttle.",
                        entryLat = 38.16080,
                        entryLon = -122.45720,
                        targetSpeed = 52.0,
                    ),
                    Corner(
                        id = 31,
                        name = "Turn 3A",
                        entryDist = 760.0,
                        apexDist = 850.0,
                        exitDist = 950.0,
                        lat = 38.16015,
                        lon = -122.45810,
                        advice = "Brake in a straight line, be patient over the crest, and let the car rotate.",
                        entryLat = 38.16030,
                        entryLon = -122.45780,
                        targetSpeed = 45.0,
                    ),
                    Corner(
                        id = 6,
                        name = "Turn 6",
                        entryDist = 1385.0,
                        apexDist = 1760.0,
                        exitDist = 2050.0,
                        lat = 38.15910,
                        lon = -122.45620,
                        advice = "Carousel: hug the inside, keep maintenance throttle, and never give up distance.",
                        entryLat = 38.15950,
                        entryLon = -122.45720,
                        targetSpeed = 65.0,
                    ),
                    Corner(
                        id = 7,
                        name = "Turn 7",
                        entryDist = 2100.0,
                        apexDist = 2190.0,
                        exitDist = 2280.0,
                        lat = 38.15950,
                        lon = -122.45400,
                        advice = "Double-apex mindset: stay tight, rotate in the middle, and use both apexes.",
                        entryLat = 38.15970,
                        entryLon = -122.45430,
                        targetSpeed = 52.0,
                    ),
                    Corner(
                        id = 910,
                        name = "Turns 9-10",
                        entryDist = 2900.0,
                        apexDist = 3230.0,
                        exitDist = 3500.0,
                        lat = 38.16040,
                        lon = -122.45320,
                        advice = "Open Turn 9, straighten the car, and sacrifice it for a clean Turn 10/11 run.",
                        entryLat = 38.16000,
                        entryLon = -122.45360,
                        targetSpeed = 58.0,
                    ),
                    Corner(
                        id = 11,
                        name = "Turn 11",
                        entryDist = 3550.0,
                        apexDist = 3700.0,
                        exitDist = 3850.0,
                        lat = 38.16100,
                        lon = -122.45300,
                        advice = "Big brake zone. Straight-line brake, patient release, and protect the exit.",
                        entryLat = 38.16120,
                        entryLon = -122.45330,
                        targetSpeed = 42.0,
                    ),
                    Corner(
                        id = 12,
                        name = "Turn 12",
                        entryDist = 3920.0,
                        apexDist = 3990.0,
                        exitDist = 4031.38,
                        lat = 38.16155,
                        lon = -122.45420,
                        advice = "Unwind early, free the hands, and commit to front-straight exit speed.",
                        entryLat = 38.16130,
                        entryLon = -122.45380,
                        targetSpeed = 80.0,
                    ),
                ),
        )

    val thunderhillEast =
        Track(
            name = "Thunderhill Raceway (East)",
            lengthMeters = 4612.0,
            centerLat = 39.540323,
            centerLon = -122.331111,
            corners =
                listOf(
                    Corner(
                        id = 1,
                        name = "Turn 1 brake",
                        entryDist = 305.0,
                        apexDist = 400.0,
                        exitDist = 505.0,
                        lat = 39.5392534,
                        lon = -122.3311847,
                        advice = "Primary brake zone after the front straight. Brake straight, release before the long exit.",
                        entryLat = 39.5401077,
                        entryLon = -122.3311918,
                        targetSpeed = 66.0,
                    ),
                    Corner(
                        id = 2,
                        name = "Turn 2",
                        entryDist = 890.0,
                        apexDist = 985.0,
                        exitDist = 1090.0,
                        lat = 39.5357876,
                        lon = -122.3277582,
                        advice = "Patient entry. Let the car rotate before asking for exit throttle.",
                        entryLat = 39.5360057,
                        entryLon = -122.3288271,
                        targetSpeed = 58.0,
                    ),
                    Corner(
                        id = 3,
                        name = "Turn 3",
                        entryDist = 1134.0,
                        apexDist = 1229.0,
                        exitDist = 1334.0,
                        lat = 39.5373403,
                        lon = -122.3270601,
                        advice = "Link the early technical section with calm hands and eyes up.",
                        entryLat = 39.5366014,
                        entryLon = -122.3265998,
                        targetSpeed = 64.0,
                    ),
                    Corner(
                        id = 4,
                        name = "Turn 4",
                        entryDist = 1321.0,
                        apexDist = 1416.0,
                        exitDist = 1521.0,
                        lat = 39.5378993,
                        lon = -122.3291086,
                        advice = "Open the steering and prepare the climb; do not add panic brake.",
                        entryLat = 39.5376189,
                        entryLon = -122.3280659,
                        targetSpeed = 68.0,
                    ),
                    Corner(
                        id = 5,
                        name = "Turn 5 setup",
                        entryDist = 1531.0,
                        apexDist = 1626.0,
                        exitDist = 1731.0,
                        lat = 39.5394314,
                        lon = -122.3287368,
                        advice = "Set the car early for the uphill transition.",
                        entryLat = 39.5388152,
                        entryLon = -122.3294795,
                        targetSpeed = 70.0,
                    ),
                    Corner(
                        id = 6,
                        name = "Turn 5 / Cyclone approach",
                        entryDist = 1723.0,
                        apexDist = 1818.0,
                        exitDist = 1923.0,
                        lat = 39.5410311,
                        lon = -122.3292300,
                        advice = "Smooth approach over elevation; keep the platform settled.",
                        entryLat = 39.5402325,
                        entryLon = -122.3288888,
                        targetSpeed = 58.0,
                    ),
                    Corner(
                        id = 7,
                        name = "Turn 5 crest",
                        entryDist = 2024.0,
                        apexDist = 2119.0,
                        exitDist = 2224.0,
                        lat = 39.5429479,
                        lon = -122.3286027,
                        advice = "Blind crest discipline: straight, smooth, and committed.",
                        entryLat = 39.5424083,
                        entryLon = -122.3294536,
                        targetSpeed = 54.0,
                    ),
                    Corner(
                        id = 8,
                        name = "Turn 5 / Cyclone exit",
                        entryDist = 2317.0,
                        apexDist = 2412.0,
                        exitDist = 2517.0,
                        lat = 39.5449015,
                        lon = -122.3304687,
                        advice = "Unwind over the crest and let the car use the road on exit.",
                        entryLat = 39.5443762,
                        entryLon = -122.3296034,
                        targetSpeed = 60.0,
                    ),
                    Corner(
                        id = 9,
                        name = "Turn 6",
                        entryDist = 2569.0,
                        apexDist = 2664.0,
                        exitDist = 2769.0,
                        lat = 39.5449707,
                        lon = -122.3333821,
                        advice = "Build speed progressively; avoid a second brake input.",
                        entryLat = 39.5450059,
                        entryLon = -122.3322789,
                        targetSpeed = 62.0,
                    ),
                    Corner(
                        id = 10,
                        name = "Turn 7",
                        entryDist = 2919.0,
                        apexDist = 3014.0,
                        exitDist = 3119.0,
                        lat = 39.5427428,
                        lon = -122.3362496,
                        advice = "Flowing section. Hold rhythm and look far through the next complex.",
                        entryLat = 39.5433657,
                        entryLon = -122.3354928,
                        targetSpeed = 74.0,
                    ),
                    Corner(
                        id = 11,
                        name = "Turn 8",
                        entryDist = 3462.0,
                        apexDist = 3557.0,
                        exitDist = 3662.0,
                        lat = 39.5380449,
                        lon = -122.3351537,
                        advice = "Left-side complex entry. Trim only while straight and keep vision long.",
                        entryLat = 39.5388213,
                        entryLon = -122.3354803,
                        targetSpeed = 68.0,
                    ),
                    Corner(
                        id = 12,
                        name = "Turn 9",
                        entryDist = 3596.0,
                        apexDist = 3691.0,
                        exitDist = 3796.0,
                        lat = 39.5379308,
                        lon = -122.3336059,
                        advice = "Finish rotation before throttle; avoid coasting at apex.",
                        entryLat = 39.5379865,
                        entryLon = -122.3347091,
                        targetSpeed = 56.0,
                    ),
                    Corner(
                        id = 13,
                        name = "Turn 10",
                        entryDist = 3778.0,
                        apexDist = 3873.0,
                        exitDist = 3978.0,
                        lat = 39.5393650,
                        lon = -122.3328372,
                        advice = "Protect the exit and unwind toward the long run home.",
                        entryLat = 39.5386566,
                        entryLon = -122.3334261,
                        targetSpeed = 62.0,
                    ),
                    Corner(
                        id = 14,
                        name = "Turn 14",
                        entryDist = 4285.0,
                        apexDist = 4380.0,
                        exitDist = 4485.0,
                        lat = 39.5439085,
                        lon = -122.3327665,
                        advice = "Fast return section. Stay precise and avoid over-slowing.",
                        entryLat = 39.5430638,
                        entryLon = -122.3328057,
                        targetSpeed = 72.0,
                    ),
                    Corner(
                        id = 15,
                        name = "Turn 15",
                        entryDist = 4441.0,
                        apexDist = 4536.0,
                        exitDist = 4612.0,
                        lat = 39.5434948,
                        lon = -122.3312813,
                        advice = "Final kink to the front straight: eyes up, free the hands, commit out.",
                        entryLat = 39.5440174,
                        entryLon = -122.3321507,
                        targetSpeed = 76.0,
                    ),
                ),
        )

    val defaultTrack: Track = sonomaRaceway

    fun fromName(name: String?): Track {
        if (name.isNullOrBlank()) return defaultTrack
        val normalized = name.trim().lowercase()
        return when {
            normalized == sonomaRaceway.name.lowercase() -> sonomaRaceway
            normalized.contains("sonoma") -> sonomaRaceway
            normalized == thunderhillEast.name.lowercase() -> thunderhillEast
            normalized.contains("thunderhill") -> thunderhillEast
            else -> defaultTrack
        }
    }
}
